/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.panel.CapNhapPhim;
import ui.panel.CapNhapPhong;
import ui.panel.CapNhapSuatChieu;
import ui.panel.ThongTinNhanVien;

/**
 *
 * @author datba
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienChinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuPhim = new javax.swing.JMenu();
        menuXuatChieu = new javax.swing.JMenu();
        mitemCapNhapXuatChieu = new javax.swing.JMenuItem();
        mitemTimKiemXuatChieu = new javax.swing.JMenuItem();
        mitemCapNhapPhim = new javax.swing.JMenuItem();
        mitemTimKiemPhim = new javax.swing.JMenuItem();
        menuPhongChieu = new javax.swing.JMenu();
        mitemCapNhapPhong = new javax.swing.JMenuItem();
        mitemTimKiemPhong = new javax.swing.JMenuItem();
        menuGhe = new javax.swing.JMenu();
        mitemCapNhapGhe = new javax.swing.JMenuItem();
        mitemTimKiemGhe = new javax.swing.JMenuItem();
        menuVeXemPhim = new javax.swing.JMenu();
        mitemDatVe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 700));

        menuPhim.setText("Phim");

        menuXuatChieu.setText("Xuất chiếu");

        mitemCapNhapXuatChieu.setText("Cập nhập");
        mitemCapNhapXuatChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemCapNhapXuatChieuActionPerformed(evt);
            }
        });
        menuXuatChieu.add(mitemCapNhapXuatChieu);

        mitemTimKiemXuatChieu.setText("Tìm kiếm");
        mitemTimKiemXuatChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemTimKiemXuatChieuActionPerformed(evt);
            }
        });
        menuXuatChieu.add(mitemTimKiemXuatChieu);

        menuPhim.add(menuXuatChieu);

        mitemCapNhapPhim.setText("Cập nhập");
        mitemCapNhapPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemCapNhapPhimActionPerformed(evt);
            }
        });
        menuPhim.add(mitemCapNhapPhim);

        mitemTimKiemPhim.setText("Tìm kiếm");
        menuPhim.add(mitemTimKiemPhim);

        jMenuBar1.add(menuPhim);

        menuPhongChieu.setText("Phòng chiếu");

        mitemCapNhapPhong.setText("Cập nhập");
        mitemCapNhapPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemCapNhapPhongActionPerformed(evt);
            }
        });
        menuPhongChieu.add(mitemCapNhapPhong);

        mitemTimKiemPhong.setText("Tìm kiếm");
        mitemTimKiemPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemTimKiemPhongActionPerformed(evt);
            }
        });
        menuPhongChieu.add(mitemTimKiemPhong);

        jMenuBar1.add(menuPhongChieu);

        menuGhe.setText("Ghế");

        mitemCapNhapGhe.setText("Cập nhập");
        mitemCapNhapGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemCapNhapGheActionPerformed(evt);
            }
        });
        menuGhe.add(mitemCapNhapGhe);

        mitemTimKiemGhe.setText("Tìm kiếm");
        mitemTimKiemGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemTimKiemGheActionPerformed(evt);
            }
        });
        menuGhe.add(mitemTimKiemGhe);

        jMenuBar1.add(menuGhe);

        menuVeXemPhim.setText("Vé xem phim");

        mitemDatVe.setText("Đặt vé");
        mitemDatVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemDatVeActionPerformed(evt);
            }
        });
        menuVeXemPhim.add(mitemDatVe);

        jMenuBar1.add(menuVeXemPhim);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitemCapNhapPhimActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mitemCapNhapPhimActionPerformed
        // TODO add your handling code here:
        removeAllComp();
        pnCapNhapPhim = new CapNhapPhim();
        add(pnCapNhapPhim, BorderLayout.CENTER);
        reLoadForm();
    }// GEN-LAST:event_mitemCapNhapPhimActionPerformed

    private void mitemCapNhapXuatChieuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mitemCapNhapXuatChieuActionPerformed
        // TODO add your handling code here:
        removeAllComp();
        pnCapNhapSuatChieu = new CapNhapSuatChieu();
        add(pnCapNhapSuatChieu);
        reLoadForm();

    }// GEN-LAST:event_mitemCapNhapXuatChieuActionPerformed

    private void mitemTimKiemXuatChieuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mitemTimKiemXuatChieuActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_mitemTimKiemXuatChieuActionPerformed

    private void mitemCapNhapPhongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mitemCapNhapPhongActionPerformed
        // TODO add your handling code here:
        removeAllComp();
        pnCapNhapPhong = new CapNhapPhong();
        add(pnCapNhapPhong);
        reLoadForm();
    }// GEN-LAST:event_mitemCapNhapPhongActionPerformed

    private void mitemTimKiemPhongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mitemTimKiemPhongActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_mitemTimKiemPhongActionPerformed

    private void mitemCapNhapGheActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mitemCapNhapGheActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_mitemCapNhapGheActionPerformed

    private void mitemTimKiemGheActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mitemTimKiemGheActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_mitemTimKiemGheActionPerformed

    private void mitemDatVeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mitemDatVeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_mitemDatVeActionPerformed

    private void mitemThemPhimActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mitemThemPhimActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_mitemThemPhimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh().setVisible(true);
            }
        });
    }

    private ThongTinNhanVien pnThongTin;
    private CapNhapPhim pnCapNhapPhim;
    private CapNhapSuatChieu pnCapNhapSuatChieu;
    private CapNhapPhong pnCapNhapPhong;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuGhe;
    private javax.swing.JMenu menuPhim;
    private javax.swing.JMenu menuPhongChieu;
    private javax.swing.JMenu menuVeXemPhim;
    private javax.swing.JMenu menuXuatChieu;
    private javax.swing.JMenuItem mitemCapNhapGhe;
    private javax.swing.JMenuItem mitemCapNhapPhim;
    private javax.swing.JMenuItem mitemCapNhapPhong;
    private javax.swing.JMenuItem mitemCapNhapXuatChieu;
    private javax.swing.JMenuItem mitemDatVe;
    private javax.swing.JMenuItem mitemTimKiemGhe;
    private javax.swing.JMenuItem mitemTimKiemPhim;
    private javax.swing.JMenuItem mitemTimKiemPhong;
    private javax.swing.JMenuItem mitemTimKiemXuatChieu;
    // End of variables declaration//GEN-END:variables

    private void reLoadForm() {
        revalidate();
        repaint();
    }

    private void removeAllComp() {
        for (Component c : getContentPane().getComponents()) {
            remove(c);
        }
    }
}
