use [Java_RapChieuPhim]

select * from [dbo].[GheSuatChieu]
select * from [dbo].[KhachHang]
select * from [dbo].[NhanVien]
select * from [dbo].[SuatChieu]
select * from [dbo].[VeXemPhim]

select * from [dbo].[PhongChieu]
insert into [dbo].[PhongChieu] values('A2', 40)
insert into [dbo].[PhongChieu] values('A3', 40)
insert into [dbo].[PhongChieu] values('B1', 30)
insert into [dbo].[PhongChieu] values('C1', 25)

select * from [dbo].[Phim]
insert into Phim 
values(N'Your Name (Kimi no Na wa)', N'Nhật Bản', '2017-1-13', 107, N'Bộ phim là câu chuyện hoán đổi cơ thể của 2 cô cậu Mitsuha - nữ sinh trung học sống ở một thị trấn nhỏ của vùng Itomori và Taki – nam sinh tại thủ đô Tokyo đầy sôi động.'
		, N'Makoto Shinkai', N'Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Narita, Aoi Yûki, Nobunaga Shimazaki, Kaito Ishikawa, Kanon Tani, Masaki Terasoma, Sayaka Ohara, Kazuhiko Inoue, ...', 13, N'Giả Tưởng, Hoạt Hình, Tâm Lý, Tình Cảm-Lãng Mạn')
insert into Phim 
values(N'Dáng Hình Thanh Âm (A Silent Voice)', N'Nhật Bản', '2017-5-12', 129, N'Cậu học trò Shoya Ishida bị bạn bè và thầy cô cô lập vì đã bắt nạt cô bạn cùng lớp bị điếc bẩm sinh Shoko Nishimiya đến nỗi cô bạn phải chuyển trường. Tình cờ, Shoya gặp lại Shoko. Shoya quyết định chuộc lại lỗi lầm năm xưa.'
		, N'Naoko Yamada', N'Miyu Irino, Saori Hayami, Aoi Yuki, Kensho Ono, Yuki Kaneko, ...', 13, N'Hoạt Hình, Tâm Lý, Tình Cảm-Lãng Mạn')
insert into Phim 
values(N'Đứa Con Của Thời Tiết (Tenki no ko)', N'Nhật Bản', '2019-8-30', 114, N'Hodaka là cậu thiếu niên sống trên một hòn đảo nhỏ, đã rời khỏi quê hương để đến Tokyo. Tại đây, cậu quen biết Hina - một cô gái kì lạ có năng lực chặn đứng cơn mưa và xua tan mây đen theo ý muốn.'
		, N'Makoto Shinkai', N'Kotaro Daigo, Nana Mori, Tsubasa Honda, Sakura Kiryu, Sei Hiraizumi, Yûki Kaji, Sumi Shimamoto, Moe Katsuragi, Ryohei Kimura, Kana Hanazawa, Ayane Sakura, ...', 13, N'Giả Tưởng, Hoạt Hình, Tâm Lý, Tình Cảm-Lãng Mạn')
insert into Phim 
values(N'Avengers: Endgame', N'Mỹ', '2019-4-18', 182, N'Sau sự kiện hủy diệt tàn khốc, vũ trụ chìm trong cảnh hoang tàn. Với sự trợ giúp của những đồng minh còn sống sót, biệt đội siêu anh hùng Avengers tập hợp một lần nữa để đảo ngược hành động của Thanos và khôi phục lại trật tự của vũ trụ.'
		, N'Joe Russo, Anthony Russo', N'Josh Brolin, Chris Pratt, Robert Downey Jr., Chris Hemsworth, Tom Hiddleston, ...', 13, N'Viễn Tưởng, Hành Động, Phiêu Lưu')
insert into Phim 
values(N'Bố già', N'Việt Nam', '2021-3-12', 128, N'Phim sẽ xoay quanh lối sống thường nhật của một xóm lao động nghèo, ở đó có bộ tứ anh em Giàu - Sang - Phú - Quý với Ba Sang sẽ là nhân vật chính, hay lo chuyện bao đồng nhưng vô cùng thương con cái.'
		, N'Vũ Ngọc Đãng & Trấn Thành', N'Trấn Thành, Tuấn Trần, Ngân Chi, NSND Ngọc Giàu, Lê Giang, Lan Phương, Hoàng Mèo, La Thành, Quốc Khánh, Lê Trang, A Quay, Bảo Phúc, ...', 13, N'Gia đình, Hài')

select * from [dbo].[Ghe]
insert into Ghe values('A', 2, 1)
insert into Ghe values('A', 3, 1)
insert into Ghe values('A', 4, 1)
insert into Ghe values('A', 5, 1)
insert into Ghe values('A', 6, 1)
insert into Ghe values('A', 7, 1)
insert into Ghe values('A', 8, 1)
insert into Ghe values('A', 9, 1)
insert into Ghe values('A', 10, 1)
insert into Ghe values('B', 1, 1)
insert into Ghe values('B', 2, 1)
insert into Ghe values('B', 3, 1)
insert into Ghe values('B', 4, 1)
insert into Ghe values('B', 5, 1)
insert into Ghe values('B', 6, 1)
insert into Ghe values('B', 7, 1)
insert into Ghe values('B', 8, 1)
insert into Ghe values('B', 9, 1)
insert into Ghe values('B', 10, 1)
insert into Ghe values('C', 1, 1)
insert into Ghe values('C', 2, 1)
insert into Ghe values('C', 3, 1)
insert into Ghe values('C', 4, 1)
insert into Ghe values('C', 5, 1)
insert into Ghe values('C', 6, 1)
insert into Ghe values('C', 7, 1)
insert into Ghe values('C', 8, 1)
insert into Ghe values('C', 9, 1)
insert into Ghe values('C', 10, 1)
insert into Ghe values('D', 1, 1)
insert into Ghe values('D', 2, 1)
insert into Ghe values('D', 3, 1)
insert into Ghe values('D', 4, 1)
insert into Ghe values('D', 5, 1)
insert into Ghe values('D', 6, 1)
insert into Ghe values('D', 7, 1)
insert into Ghe values('D', 8, 1)
insert into Ghe values('D', 9, 1)
insert into Ghe values('D', 10, 1)

insert into Ghe values('A', 1, 2)
insert into Ghe values('A', 2, 2)
insert into Ghe values('A', 3, 2)
insert into Ghe values('A', 4, 2)
insert into Ghe values('A', 5, 2)
insert into Ghe values('A', 6, 2)
insert into Ghe values('A', 7, 2)
insert into Ghe values('A', 8, 2)
insert into Ghe values('A', 9, 2)
insert into Ghe values('A', 10, 2)
insert into Ghe values('B', 1, 2)
insert into Ghe values('B', 2, 2)
insert into Ghe values('B', 3, 2)
insert into Ghe values('B', 4, 2)
insert into Ghe values('B', 5, 2)
insert into Ghe values('B', 6, 2)
insert into Ghe values('B', 7, 2)
insert into Ghe values('B', 8, 2)
insert into Ghe values('B', 9, 2)
insert into Ghe values('B', 10, 2)
insert into Ghe values('C', 1, 2)
insert into Ghe values('C', 2, 2)
insert into Ghe values('C', 3, 2)
insert into Ghe values('C', 4, 2)
insert into Ghe values('C', 5, 2)
insert into Ghe values('C', 6, 2)
insert into Ghe values('C', 7, 2)
insert into Ghe values('C', 8, 2)
insert into Ghe values('C', 9, 2)
insert into Ghe values('C', 10, 2)
insert into Ghe values('D', 1, 2)
insert into Ghe values('D', 2, 2)
insert into Ghe values('D', 3, 2)
insert into Ghe values('D', 4, 2)
insert into Ghe values('D', 5, 2)
insert into Ghe values('D', 6, 2)
insert into Ghe values('D', 7, 2)
insert into Ghe values('D', 8, 2)
insert into Ghe values('D', 9, 2)
insert into Ghe values('D', 10, 2)

insert into Ghe values('A', 1, 3)
insert into Ghe values('A', 2, 3)
insert into Ghe values('A', 3, 3)
insert into Ghe values('A', 4, 3)
insert into Ghe values('A', 5, 3)
insert into Ghe values('A', 6, 3)
insert into Ghe values('A', 7, 3)
insert into Ghe values('A', 8, 3)
insert into Ghe values('A', 9, 3)
insert into Ghe values('A', 10, 3)
insert into Ghe values('B', 1, 3)
insert into Ghe values('B', 2, 3)
insert into Ghe values('B', 3, 3)
insert into Ghe values('B', 4, 3)
insert into Ghe values('B', 5, 3)
insert into Ghe values('B', 6, 3)
insert into Ghe values('B', 7, 3)
insert into Ghe values('B', 8, 3)
insert into Ghe values('B', 9, 3)
insert into Ghe values('B', 10, 3)
insert into Ghe values('C', 1, 3)
insert into Ghe values('C', 2, 3)
insert into Ghe values('C', 3, 3)
insert into Ghe values('C', 4, 3)
insert into Ghe values('C', 5, 3)
insert into Ghe values('C', 6, 3)
insert into Ghe values('C', 7, 3)
insert into Ghe values('C', 8, 3)
insert into Ghe values('C', 9, 3)
insert into Ghe values('C', 10, 3)

insert into Ghe values('A', 1, 4)
insert into Ghe values('A', 2, 4)
insert into Ghe values('A', 3, 4)
insert into Ghe values('A', 4, 4)
insert into Ghe values('A', 5, 4)
insert into Ghe values('B', 1, 4)
insert into Ghe values('B', 2, 4)
insert into Ghe values('B', 3, 4)
insert into Ghe values('B', 4, 4)
insert into Ghe values('B', 5, 4)
insert into Ghe values('C', 1, 4)
insert into Ghe values('C', 2, 4)
insert into Ghe values('C', 3, 4)
insert into Ghe values('C', 4, 4)
insert into Ghe values('C', 5, 4)
insert into Ghe values('D', 1, 4)
insert into Ghe values('D', 2, 4)
insert into Ghe values('D', 3, 4)
insert into Ghe values('D', 4, 4)
insert into Ghe values('D', 5, 4)
insert into Ghe values('E', 1, 4)
insert into Ghe values('E', 2, 4)
insert into Ghe values('E', 3, 4)
insert into Ghe values('E', 4, 4)
insert into Ghe values('E', 5, 4)

delete Phim

DBCC CHECKIDENT ('[dbo].[Ghe]', RESEED, 0)
DBCC CHECKIDENT ('[dbo].[GheSuatChieu]', RESEED, 0)
DBCC CHECKIDENT ('[dbo].[KhachHang]', RESEED, 0)
DBCC CHECKIDENT ('[dbo].[NhanVien]', RESEED, 0)
DBCC CHECKIDENT ('[dbo].[Phim]', RESEED, 0)
DBCC CHECKIDENT ('[dbo].[PhongChieu]', RESEED, 0)
DBCC CHECKIDENT ('[dbo].[SuatChieu]', RESEED, 0)
DBCC CHECKIDENT ('[dbo].[VeXemPhim]', RESEED, 0)
